services:
  go-vod:
    container_name: go-vod
    devices:
      - /dev/dri:/dev/dri
    environment:
      - NEXTCLOUD_ALLOW_INSECURE=1
      - NEXTCLOUD_HOST=https://nextcloud
      - NVIDIA_VISIBLE_DEVICES=all
    image: radialapps/go-vod
    init: true
    ports:
      - 47788:47788
    restart: always
    volumes:
      - /var/www/html:/var/www/html:ro
    # runtime: nvidia # (NVENC)
