name: nextcloud
services:
  nextcloud:
    container_name: nextcloud
    depends_on:
      - nextcloud-postgresql
      - nextcloud-valkey
    devices:
      - /dev/dri:/dev/dri
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=
      - PGID=$PGID
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=nextcloud-postgresql
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_USER=nextcloud
      - PUID=$PUID
      - REDIS_HOST=nextcloud-valkey
      - REDIS_HOST_PORT=6379
      - TZ=$TZ
    image: nextcloud:29.0.0
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/icon.png
    ports:
      - protocol: tcp
        published: 10081
        target: 80
      - protocol: tcp
        published: 10443
        target: 443
    restart: unless-stopped
    volumes:
      - source: /DATA/AppData/nextcloud-md/var/www/html
        target: /var/www/html
        type: bind
      - source: /DATA/nextcloud-md/data
        target: /var/www/data
        type: bind
  nextcloud-go-vod:
    container_name: nextcloud-go-vod
    depends_on:
      - nextcloud
    devices:
      - /dev/dri:/dev/dri
    environment:
      - NEXTCLOUD_ALLOW_INSECURE=true
      - NEXTCLOUD_HOST=http://nextcloud
      - NVIDIA_VISIBLE_DEVICES=all
    image: radialapps/go-vod:0.2.5
    init: true
    restart: always
    volumes:
      - read_only: true
        source: /DATA/AppData/nextcloud-md/var/www/html
        target: /var/www/html
        type: bind
  nextcloud-postgresql:
    container_name: nextcloud-postgresql
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_USER=nextcloud
      - TZ=$TZ
    hostname: nextcloud-postgresql
    image: postgres:15.3
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PostgreSQL/icon.png
    ports:
      - protocol: tcp
        published: 5432
        target: 5432
    restart: unless-stopped
    volumes:
      - source: /DATA/AppData/nextcloud-postgresql/data
        target: /var/lib/postgresql/data
        type: bind
  nextcloud-valkey:
    container_name: nextcloud-valkey
    hostname: nextcloud-valkey
    image: valkey/valkey:7.2.5
    labels:
      icon: https://valkey.io/assets/img/Valkey-logo.svg
    ports:
      - protocol: tcp
        published: 6379
        target: 6379
    privileged: false
    restart: unless-stopped
    volumes:
      - source: /DATA/AppData/nextcloud-valkey/data
        target: /data
        type: bind
      - source: /DATA/AppData/nextcloud-valkey/config
        target: /usr/local/etc/valkey
        type: bind
